### ISSUE TITLE
Недочёты

### ISSUE THREAD

**Issue by Sonahit** [Lokilife/patriot#1]
# Недочёты

## index.js
В файле index.js есть такой код

```js
//Обработчик событий
const files_events = requireAll({
  dirname: `${__dirname}/events`,
  filter: /^(?!-)(.+)\.js$/
});
for (const name in files_events) {
  const event = files_events[name];
  client.on(name, event.bind(null, client));
}
//Обработчик команд
client.commands = new Discord.Collection()
let files_cmds = fs.readdir("./cmds",(err,files)=>{
	if(err) throw err;
	let jsfile = files.filter(f => f.split('.').pop() === "js")
	jsfile.forEach((f, i) =>{
		let props = require(`./cmds/${f}`)
		client.commands.set(props.help.name,props)
	})
});
```
Этот код можно сделать лучше!

```js
//Обработчик событий
const files_events = requireAll({
  dirname: `${__dirname}/events`,
  filter: /^(?!-)(.+)\.js$/
});
```
Этот код, выглядит нормально.

Есть проблемы в этом коде

```js
//Обработчик команд
client.commands = new Discord.Collection()
let files_cmds = fs.readdir("./cmds",(err,files)=>{
	if(err) throw err;
	let jsfile = files.filter(f => f.split('.').pop() === "js")
	jsfile.forEach((f, i) =>{
		let props = require(`./cmds/${f}`)
		client.commands.set(props.help.name,props)
	})
});
```
1. Для того, чтобы не писать постоянно путь можно было сделать отдельную переменную
```js
// Нормально
let commandsDirectory = "./cmds";
// Хорошо
const commandsDirectory = "./cmds";
// Хорошо
const commandsDirectory = `${__dirname}/cmd`;
```
И уже использовать. Это тебе дало то, что имеется понимание за что отвечает эта переменная.

2. Почему используется уже fs, а не библиотека requireAll и почему нельзя сразу записать в свойство?

Это можно было и замечательно переделать при помощи этой библиотеки и сразу записать в свойство
```js
const commandsDirectory = `${__dirname}/cmd`;
client.commands = new Discord.Collection(Object.values(requireAll({
  dirname: commandsDirectory,
  filter: /^(?!-)(.+)\.js$/,
  resolve: cmd => {
    return [cmd.help.name, cmd]
  }
})));
```
И это будет работать также как и предыдущий код
https://stackoverflow.com/questions/32877552/how-to-initialize-a-map-in-es6-es2015-similar-to-an-object-expression

## Остальные файлы
В остальных файлах такая же история

1. Неправильные названия переменных
2. Неиспользование деструктуризации
3. В некоторых файлов постоянных вызов кэша, когда его можно записать в переменную, то это позволить уменьшить сложность чтения кода.

## Замечания
Добавлю несколько замечаний

1. Все переменные должны быть в camelCase или должны быть стилизированы по одному стилю, а не по нескольким snake_case + camelCase!. Выбери что-то одно и ступай с этим по всему коду, так как я заметил, что у тебя идёт микс snake_case и camelCase
2. Когда написал какой-то кусок кода и считаешь, что его можно улучшить, то улучшая. Не нужно бросать дела на словах - "И так сойдёт".
3. Не рекомендую думать и считать, что ты пишешь код для себя, то его можно писать со многими антипаттернами. Если ты избавишься от этого мышления, то у тебя появится чистый код, который ты сможешь развить дисциплину и свой хороший стиль написания кода, а также прочитать спустя и 1 год твоей карьеры программиста.

**Comment by Lokilife** [comment]
Спасибо за замечания, но я этого бота уже давно перестал писать и решил начать нормально изучить JavaScript чтобы не было подобных недочётов и был нормальный код. В скором времени этот бот будет удалён с Github.

Спасибо за внимание.
